/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modulo_productos;

import comandosSQL.conexion;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JTable;

/**
 *
 * @author William May
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        this.setLocationRelativeTo(this);
        conexion con = new conexion();
        con.RellenaLaTablaConDatosMySQL("productos", jtable_inicio);
        jtable_inicio.addMouseListener(new MouseAdapter(){
            public void mousePressed(MouseEvent Mouse_evt)
                {
                    JTable table = (JTable) Mouse_evt.getSource();
                    Point point = Mouse_evt.getPoint();
                    int row = table.rowAtPoint(point);
                    if(Mouse_evt.getClickCount() == 1)
               
                {
                    eliminar_producto.setEnabled(true);
                    actualizar_producto.setEnabled(true);
                    jnombre.setText(jtable_inicio.getValueAt(jtable_inicio.getSelectedRow(), 1).toString());
                    jcodigo.setText(jtable_inicio.getValueAt(jtable_inicio.getSelectedRow(), 2).toString());
                    jcategoria.setText(jtable_inicio.getValueAt(jtable_inicio.getSelectedRow(), 3).toString());
                    jprecio.setText(jtable_inicio.getValueAt(jtable_inicio.getSelectedRow(), 4).toString());
                }
                }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_inicio = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jnombre = new javax.swing.JTextField();
        jcodigo = new javax.swing.JTextField();
        jcategoria = new javax.swing.JTextField();
        jprecio = new javax.swing.JTextField();
        eliminar_producto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        guardar_producto1 = new javax.swing.JButton();
        actualizar_producto = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jtable_inicio.setBackground(new java.awt.Color(0, 0, 0));
        jtable_inicio.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jtable_inicio.setForeground(new java.awt.Color(255, 255, 255));
        jtable_inicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtable_inicio.setCellSelectionEnabled(true);
        jtable_inicio.setGridColor(new java.awt.Color(255, 0, 0));
        jtable_inicio.setInheritsPopupMenu(true);
        jtable_inicio.setSelectionBackground(new java.awt.Color(238, 238, 238));
        jtable_inicio.setSelectionForeground(new java.awt.Color(255, 0, 0));
        jScrollPane1.setViewportView(jtable_inicio);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Código:");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Categoria:");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio:");

        jnombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jnombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jcodigo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jcodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jcategoria.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jcategoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jprecio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jprecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        eliminar_producto.setBackground(new java.awt.Color(255, 0, 102));
        eliminar_producto.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        eliminar_producto.setForeground(new java.awt.Color(255, 255, 255));
        eliminar_producto.setText("Eliminar");
        eliminar_producto.setBorder(null);
        eliminar_producto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        eliminar_producto.setEnabled(false);
        eliminar_producto.setFocusPainted(false);
        eliminar_producto.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        eliminar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_productoActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Blockys St", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BASE DE DATOS");

        guardar_producto1.setBackground(new java.awt.Color(249, 115, 0));
        guardar_producto1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        guardar_producto1.setForeground(new java.awt.Color(255, 255, 255));
        guardar_producto1.setText("Guardar");
        guardar_producto1.setBorder(null);
        guardar_producto1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        guardar_producto1.setFocusPainted(false);
        guardar_producto1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        guardar_producto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_producto1ActionPerformed(evt);
            }
        });

        actualizar_producto.setBackground(new java.awt.Color(249, 115, 0));
        actualizar_producto.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        actualizar_producto.setForeground(new java.awt.Color(255, 255, 255));
        actualizar_producto.setText("Actualizar");
        actualizar_producto.setBorder(null);
        actualizar_producto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        actualizar_producto.setEnabled(false);
        actualizar_producto.setFocusPainted(false);
        actualizar_producto.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        actualizar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizar_productoActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(51, 51, 255));
        btnSalir.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(guardar_producto1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(eliminar_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(actualizar_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcodigo)
                            .addComponent(jLabel3)
                            .addComponent(jcategoria)
                            .addComponent(jprecio))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)
                        .addComponent(jnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminar_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualizar_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardar_producto1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_productoActionPerformed
        // TODO add your handling code here:
        String id = jtable_inicio.getValueAt(jtable_inicio.getSelectedRow(), 0).toString();
        conexion con = new conexion();
        con.EliminaRegistro(id);
        con.RellenaLaTablaConDatosMySQL("productos", jtable_inicio);
    }//GEN-LAST:event_eliminar_productoActionPerformed

    private void guardar_producto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_producto1ActionPerformed
        // TODO add your handling code here:
        conexion con = new conexion();
        con.InsertarRegistroConProcedimientoAlmacenado(jnombre, jcodigo, jcategoria, jprecio);
        con.RellenaLaTablaConDatosMySQL("productos", jtable_inicio);
        jnombre.setText("");
        jcodigo.setText("");
        jcategoria.setText("");
        jprecio.setText("");
    }//GEN-LAST:event_guardar_producto1ActionPerformed

    private void actualizar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizar_productoActionPerformed
        // TODO add your handling code here:
        conexion con = new conexion();
        String id = jtable_inicio.getValueAt(jtable_inicio.getSelectedRow(), 0).toString();
        con.ActualizarProducto(jnombre, jcodigo, jcategoria, jprecio, id);
        con.RellenaLaTablaConDatosMySQL("productos", jtable_inicio);
        jnombre.setText("");
        jcodigo.setText("");
        jcategoria.setText("");
        jprecio.setText("");
    }//GEN-LAST:event_actualizar_productoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar_producto;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton eliminar_producto;
    private javax.swing.JButton guardar_producto1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jcategoria;
    private javax.swing.JTextField jcodigo;
    private javax.swing.JTextField jnombre;
    private javax.swing.JTextField jprecio;
    private javax.swing.JTable jtable_inicio;
    // End of variables declaration//GEN-END:variables
}
